"""Run the isolated HTML prototype checks; no API or personal profile access."""
from pathlib import Path
import json
import os
from playwright.sync_api import sync_playwright

ROOT = Path(__file__).resolve().parents[3]
HTML = Path(__file__).with_name('index.html')
EVIDENCE = ROOT / 'artifacts/visual-evidence/issue-177'
EVIDENCE.mkdir(parents=True, exist_ok=True)
CHROME = os.environ.get('PROTOTYPE_CHROME', '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome')
results = []


def check(name, condition):
    assert condition, name
    results.append(name)


def no_overflow(page, name):
    check(name, page.evaluate('document.documentElement.scrollWidth <= innerWidth') and page.locator('.prototype-dialog[open], .prototype-dialog[open] .row > button, .prototype-dialog[open] .row strong').evaluate_all('(nodes) => nodes.every(n => n.scrollWidth <= n.clientWidth)'))


with sync_playwright() as p:
    browser = p.chromium.launch(executable_path=CHROME, headless=True)
    context = browser.new_context(viewport={'width': 390, 'height': 844}, locale='ru-RU', reduced_motion='reduce')
    page = context.new_page()
    errors = []
    page.on('pageerror', lambda error: errors.append(str(error)))
    # Reject any network access. Local CSS and fonts load via file:// only.
    context.route('http://**/*', lambda route: route.abort())
    context.route('https://**/*', lambda route: route.abort())
    page.goto(HTML.as_uri())
    page.evaluate('document.fonts.ready')
    check('Manrope loaded', page.evaluate('document.fonts.check("16px PrototypeManrope")'))
    check('four quadrants show at most three tasks', page.locator('.quadrant').evaluate_all('(nodes) => nodes.map(n => n.querySelectorAll(".cell-task").length)') == [3, 2, 2, 1])
    check('no duplicate category headings or separate selected list', page.locator('.quadrant-title:visible, #selected-tasks, .quadrant .number, .quadrant .coordinate').count() == 0)
    check('quadrants retain accessible category names', page.locator('.quadrant').evaluate_all('(nodes) => nodes.every(n => n.getAttribute("aria-label"))'))
    check('importance column headers visible', page.locator('.matrix-columns').is_visible() and page.locator('.matrix-columns span').all_text_contents() == ['Важное', 'Неважное'])
    check('urgency row headers visible', page.locator('.matrix-row-label.urgent').is_visible() and page.locator('.matrix-row-label.not-urgent').is_visible())
    check('matrix has common frame and cross dividers', page.locator('.matrix-grid').evaluate('(node) => { const s=getComputedStyle(node); return s.borderTopWidth === "2px" && s.gap === "2px"; }'))
    check('category geometry matches axes', page.locator('.quadrant').evaluate_all('(nodes) => { const r=nodes.map(n=>n.getBoundingClientRect()); return r[0].top === r[1].top && r[2].top === r[3].top && r[0].left === r[2].left && r[1].left === r[3].left && r[0].top < r[2].top; }'))
    check('three unclassified tasks', '3' in page.locator('.unrated summary').inner_text())
    check('deadline order in quadrant preview', page.locator('.quadrant[data-category="0"] .cell-task').evaluate_all('(nodes) => nodes.map(n => n.dataset.open)') == ['01', '02', '13'])
    check('only overflowing category has more button', page.locator('.cell-more').all_text_contents() == ['Ещё 2'])
    check('preview keeps blocker but omits duplicate priority badges', page.locator('.quadrant .mark').all_text_contents() == ['Блокер'])
    no_overflow(page, '390px matrix fits')
    page.screenshot(path=str(EVIDENCE / 'matrix-390.png'), full_page=True)

    page.locator('[data-more="0"]').focus()
    page.keyboard.press('Enter')
    check('more opens full ordered category only', page.locator('#category-tasks .row').evaluate_all('(nodes) => nodes.map(n => n.dataset.id)') == ['01', '02', '13', '14', '15'])
    check('more opens a native modal', page.locator('#category-dialog').evaluate('(node) => node.matches(":modal")'))
    page.screenshot(path=str(EVIDENCE / 'matrix-more-390.png'))
    page.locator('#category-tasks [data-open="14"]').click()
    check('hidden preview task opens its original detail', page.evaluate('currentTask().id === "14"'))
    page.locator('[data-action="back"]').click()
    check('back restores full category and task focus', page.evaluate('document.getElementById("category-dialog").open && document.activeElement.dataset.open === "14"'))
    page.keyboard.press('Escape')
    check('Escape restores more button focus', page.evaluate('expandedCategory === null && document.activeElement.dataset.more === "0"'))
    page.get_by_role('button', name='Мои', exact=True).click()
    check('exactly three matching tasks need no more button', page.locator('.quadrant[data-category="0"] .cell-task').count() == 3 and page.locator('.cell-more').count() == 0)
    page.get_by_role('button', name='Все', exact=True).click()
    page.get_by_role('searchbox', name='Поиск задач').fill('бюджет')
    check('search exposes matching task without duplicates or more', page.locator('.cell-task').evaluate_all('(nodes) => nodes.map(n => n.dataset.open)') == ['14'] and page.locator('.cell-more').count() == 0 and page.locator('.cell-empty').count() == 3)
    page.get_by_role('searchbox', name='Поиск задач').fill('')
    page.locator('.cell-task[data-open="01"]').click()
    check('preview opens original detail', page.evaluate('currentTask().id === "01"'))
    page.locator('[data-action="back"]').click()
    check('back restores preview task focus', page.evaluate('document.activeElement.dataset.open === "01"'))

    page.get_by_role('button', name='Список', exact=True).click()
    check('all thirteen active demo tasks in list', page.locator('.row').count() == 13)
    check('four list sections in agreed order', page.locator('.group').evaluate_all('(nodes) => nodes.map(n => n.dataset.category)') == ['0', '1', '2', '3'])
    check('no duplicate task IDs', page.locator('.row').evaluate_all('(nodes) => new Set(nodes.map(n => n.dataset.id)).size === nodes.length'))
    page.screenshot(path=str(EVIDENCE / 'list-390.png'), full_page=True)
    page.locator('[data-open="01"]').click()
    page.screenshot(path=str(EVIDENCE / 'details-390.png'), full_page=True)
    page.locator('[data-action="priority"]').click()
    page.screenshot(path=str(EVIDENCE / 'priority-390.png'))
    for _ in range(14):
        page.keyboard.press('Tab')
        # Native dialogs allow browser chrome focus (reported as BODY), but not background controls.
        check(f'modal Tab {len(results)} does not reach background controls', page.evaluate('document.getElementById("priority-dialog").matches(":modal") && (document.activeElement === document.body || document.getElementById("priority-dialog").contains(document.activeElement))'))
    # Cancel must not change the current task.
    page.locator('[name="importance"][value="false"]').check()
    page.get_by_role('button', name='Отмена', exact=True).click()
    check('cancel preserves task', page.evaluate('currentTask().importance === true'))
    page.locator('[data-action="priority"]').click()
    page.locator('[name="importance"][value="false"]').check()
    page.keyboard.press('Escape')
    check('Escape cancels and restores focus', page.evaluate('currentTask().importance === true && document.activeElement.dataset.action === "priority"'))

    # Exercise every pair through actual controls, including all partial states.
    for importance in ['true', 'false', 'null']:
        for urgency in ['true', 'false', 'null']:
            page.locator('[data-action="priority"]').click()
            page.locator(f'[name="importance"][value="{importance}"]').check()
            page.locator(f'[name="urgency"][value="{urgency}"]').check()
            page.get_by_role('button', name='Применить', exact=True).click()
            check(f'pair {importance}/{urgency} saved on exact task', page.evaluate('([i,u]) => currentTask().id === "01" && currentTask().importance === JSON.parse(i) && currentTask().urgency === JSON.parse(u)', [importance, urgency]))
            check(f'pair {importance}/{urgency} preserves independent fields', page.evaluate('currentTask().due === "2026-10-08" && currentTask().status === "todo" && tasks.find(t => t.id === "02").urgency === true'))
    page.locator('[data-action="priority"]').click()
    page.locator('[name="urgency"][value="true"]').check()
    page.get_by_role('button', name='Применить', exact=True).click()
    check('partial urgent state remains unclassified', page.locator('.priority-property').inner_text().find('Не разобрано') >= 0 and 'Срочная' in page.locator('.priority-property').inner_text())
    page.locator('[data-action="priority"]').click()
    page.get_by_role('button', name='Сбросить оценку', exact=True).click()
    page.get_by_role('button', name='Применить', exact=True).click()
    check('reset both fields only', page.evaluate('currentTask().importance === null && currentTask().urgency === null && currentTask().due === "2026-10-08"'))
    page.locator('[data-action="back"]').click()
    page.locator('.unrated summary').click()
    page.locator('[data-open="01"]').click()
    check('reopen reads shared state', page.evaluate('currentTask().importance === null && currentTask().urgency === null'))

    page.locator('#review-controls').evaluate('(node) => node.open = true')
    page.locator('#scenario').select_option('save-error')
    page.locator('[data-action="priority"]').click()
    page.locator('[name="importance"][value="true"]').check()
    page.get_by_role('button', name='Применить', exact=True).click()
    check('save failure does not commit', page.evaluate('currentTask().importance === null && pending.importance === true'))
    page.screenshot(path=str(EVIDENCE / 'save-error-390.png'), full_page=True)
    page.locator('[data-action="discard-save"]').click()
    check('discard preserves previous state', page.evaluate('pending === null && currentTask().importance === null'))
    page.locator('#scenario').select_option('conflict')
    page.locator('[data-action="priority"]').click()
    page.locator('[name="importance"][value="false"]').check()
    page.get_by_role('button', name='Применить', exact=True).click()
    page.screenshot(path=str(EVIDENCE / 'conflict-390.png'), full_page=True)
    page.locator('[data-action="retry-save"]').click()
    check('explicit conflict choice commits demo draft', page.evaluate('currentTask().importance === false && pending === null'))
    page.locator('#scenario').select_option('readonly')
    check('readonly disables edit', page.locator('[data-action="priority"]').is_disabled())
    page.screenshot(path=str(EVIDENCE / 'readonly-390.png'), full_page=True)

    # Fresh fixture for responsive and list/filter checks.
    page.reload()
    page.locator('#review-controls').evaluate('(node) => node.open = true')
    page.get_by_role('button', name='Фильтры', exact=True).click()
    page.locator('#status-filter').select_option('done')
    page.get_by_role('button', name='Показать задачи', exact=True).click()
    check('done filter retains category and excludes archive', page.locator('.quadrant .cell-task').evaluate_all('(nodes) => nodes.map(n => n.dataset.open)') == ['11'])
    page.get_by_role('button', name='Матрица', exact=True).click()
    check('view does not clear filter', page.evaluate('filters.status === "done"'))
    page.get_by_role('button', name='Фильтры', exact=True).click()
    page.locator('#status-filter').select_option('active')
    page.locator('#urgency-filter').select_option('true')
    page.locator('#unrated-filter').check()
    page.get_by_role('button', name='Показать задачи', exact=True).click()
    check('partial urgency filter', page.locator('.row').evaluate_all('(nodes) => nodes.map(n => n.dataset.id)') == ['08'])
    page.get_by_role('button', name='Мои', exact=True).click()
    check('scope preserves priority filter', page.evaluate('filters.urgency === "true" && filters.unrated'))
    page.reload()
    page.locator('#review-controls').evaluate('(node) => node.open = true')
    for state in ['loading', 'error', 'empty']:
        page.locator('#scenario').select_option(state)
        check(f'{state} state has no misleading task rows', page.locator('.row, .cell-task, .cell-more').count() == 0)
        page.screenshot(path=str(EVIDENCE / f'{state}-390.png'), full_page=True)
    page.locator('#scenario').select_option('ready')
    page.locator('#review-controls').evaluate('(node) => node.open = false')
    page.set_viewport_size({'width': 320, 'height': 740})
    no_overflow(page, '320px matrix fits')
    check('320px retains two columns at 100%', page.locator('.matrix-grid').evaluate('(node) => getComputedStyle(node).gridTemplateColumns.split(" ").length === 2'))
    page.screenshot(path=str(EVIDENCE / 'matrix-320.png'), full_page=True)
    page.locator('[data-more="0"]').click()
    no_overflow(page, '320px full category fits')
    page.screenshot(path=str(EVIDENCE / 'matrix-more-320.png'))
    page.locator('#close-category').click()
    check('close button restores more focus', page.evaluate('document.activeElement.dataset.more === "0"'))
    page.screenshot(path=str(EVIDENCE / 'long-text-320.png'), full_page=True)
    page.locator('[data-open="05"]').click()
    no_overflow(page, 'long detail title fits 320px')
    page.screenshot(path=str(EVIDENCE / 'details-long-320.png'), full_page=True)
    page.locator('[data-action="priority"]').click()
    no_overflow(page, 'priority dialog fits 320px')
    page.screenshot(path=str(EVIDENCE / 'priority-320.png'))
    page.keyboard.press('Escape')
    page.locator('#comment').fill('Длинный текст для проверки ввода. ' * 20)
    page.set_viewport_size({'width': 320, 'height': 360})
    page.locator('#comment').focus()
    page.locator('#comment').scroll_into_view_if_needed()
    check('short viewport can reach focused input', page.locator('#comment').evaluate('(node) => { const r=node.getBoundingClientRect(); return r.top >= 0 && r.bottom <= innerHeight; }'))
    page.screenshot(path=str(EVIDENCE / 'short-viewport-320.png'), full_page=True)
    page.set_viewport_size({'width': 320, 'height': 740})
    page.locator('[data-action="back"]').click()
    page.evaluate('document.documentElement.setAttribute("data-large", "")')
    page.wait_for_function('getComputedStyle(document.querySelector(".matrix-grid")).gridTemplateColumns.split(" ").length === 1')
    no_overflow(page, '320px 200% text fits')
    columns = page.locator('.matrix-grid').evaluate('(node) => ({columns: getComputedStyle(node).gridTemplateColumns, font: getComputedStyle(document.documentElement).fontSize, width: node.clientWidth})')
    print('200% layout:', columns)
    page.screenshot(path=str(EVIDENCE / 'diagnostic-text200.png'), full_page=True)
    check('200% text creates single column', len(columns['columns'].split()) == 1)
    check('one-column layout hides misleading axis headers', not page.locator('.matrix-columns').is_visible() and not page.locator('.matrix-row-label.urgent').is_visible())
    check('one-column layout labels all categories', page.locator('.quadrant-title:visible').count() == 4)
    page.screenshot(path=str(EVIDENCE / 'matrix-320-text200.png'), full_page=True)
    page.locator('[data-more="0"]').click()
    no_overflow(page, '200% full category fits')
    page.locator('#category-tasks [data-open="15"]').scroll_into_view_if_needed()
    check('200% last category task reachable', page.locator('#category-tasks [data-open="15"]').evaluate('(node) => { const r=node.getBoundingClientRect(); return r.top < innerHeight && r.bottom > 0; }'))
    page.screenshot(path=str(EVIDENCE / 'matrix-more-320-text200.png'))
    page.keyboard.press('Escape')
    page.locator('[data-open="05"]').click()
    no_overflow(page, '200% long detail fits')
    page.locator('[data-action="priority"]').click()
    no_overflow(page, '200% priority dialog fits')
    page.screenshot(path=str(EVIDENCE / 'priority-320-text200.png'))
    page.locator('#priority-dialog').evaluate('(node) => node.scrollTop = node.scrollHeight')
    page.screenshot(path=str(EVIDENCE / 'priority-320-text200-bottom.png'))
    check('200% dialog bottom actions reachable', page.get_by_role('button', name='Отмена', exact=True).evaluate('(node) => { const r = node.getBoundingClientRect(); return r.top >= 0 && r.bottom <= innerHeight; }'))
    page.keyboard.press('Escape')
    page.reload()
    page.get_by_role('button', name='＋ Новая задача', exact=True).click()
    check('new task starts unknown', page.evaluate('currentTask().importance === null && currentTask().urgency === null'))
    page.locator('#new-title').fill('Новая демонстрационная задача')
    page.locator('[data-action="priority"]').click()
    page.locator('[name="importance"][value="true"]').check()
    page.get_by_role('button', name='Применить', exact=True).click()
    page.screenshot(path=str(EVIDENCE / 'create-320.png'), full_page=True)
    page.get_by_role('button', name='Создать в демо', exact=True).click()
    check('creation keeps partial assessment', page.evaluate('!creating && currentTask().importance === true && currentTask().urgency === null'))
    check('no uncaught browser errors', not errors)
    evidence = {'scope': 'HTML prototype only; no API/DB/Telegram claims', 'browser': browser.version, 'checks': results, 'count': len(results), 'screenshots': sorted(path.name for path in EVIDENCE.glob('*.png')), 'errors': errors}
    (EVIDENCE / 'checks.json').write_text(json.dumps(evidence, ensure_ascii=False, indent=2) + '\n')
    print(json.dumps(evidence, ensure_ascii=False, indent=2))
    browser.close()
