import { expect, test } from '@playwright/test';
import { createHash, randomBytes, randomUUID } from 'node:crypto';
import { mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { buildApp } from '../../api/src/app';
import { connectChatBoard, createDatabase, createTask, login } from '../../api/src/db';
import type { Config } from '../../api/src/config';

const evidence = fileURLToPath(new URL('../../../artifacts/visual-evidence/', import.meta.url));
const url = process.env.TEST_DATABASE_URL;
if (!url) throw new Error('TEST_DATABASE_URL is required for directions browser/API/DB tests');
for (const width of [390, 320]) test(`chat directions: entry, confirmation, lost response, selection and revocation ${width}`, async ({page}) => {
  const db = createDatabase(url);
  const stamp = randomBytes(6).readUIntBE(0, 6);
  const config: Config = {botToken: 'test', databaseUrl: url, sessionSecret: 'isolated-directions-visual', initDataMaxAgeSeconds: 60, sessionMaxAgeSeconds: 3600,
    host: '127.0.0.1', port: 0, production: false, webhookSecret: 'isolated-webhook', publicUrl: 'https://example.test', botUsername: 'test_bot'};
  const owner = await login(db, {id: stamp, first_name: 'Администратор'}, 3600, config.sessionSecret);
  const member = await login(db, {id: stamp + 1, first_name: 'Участник с длинным именем'}, 3600, config.sessionSecret);
  const root = (await connectChatBoard(db, -stamp, 'Команда «Направления»'))!;
  const app = buildApp(config, db);
  let person = owner, startToken = '', lost = false;
  let common = '';
  const direct = 'board_' + randomBytes(24).toString('base64url');
  const originalFetch = globalThis.fetch;
  const creates: any[] = [], errors: string[] = [];
  globalThis.fetch = (async (input, options) => {
    if (!String(input).endsWith('/getChatMember')) throw new Error('No Telegram sends allowed');
    return Response.json({ok: true, result: {status: String(JSON.parse(String(options?.body)).user_id) === String(stamp) ? 'administrator' : 'member'}});
  }) as typeof fetch;
  try {
    await db.query("UPDATE boards SET status = 'active' WHERE id = $1", [root.id]);
    for (const user of [owner, member]) await db.query("INSERT INTO memberships VALUES ($1,$2,'member')", [root.id, user.userId]);
    await db.query("INSERT INTO board_links (token_hash,board_id,kind) VALUES ($1,$2,'launch')", [createHash('sha256').update(direct).digest('hex'), root.id]);
    startToken = direct;
    await createTask(db, owner.userId, root.id, {title: 'Исходная задача'});
    await page.setViewportSize({width, height: 844});
    page.on('pageerror', error => errors.push(error.message));
    await page.route('https://telegram.org/js/telegram-web-app.js', route => route.fulfill({contentType: 'application/javascript', body: `window.Telegram={WebApp:{initData:'isolated',initDataUnsafe:{start_param:${JSON.stringify(startToken)}},ready(){},expand(){}}};`}));
    await page.route('**/api/**', async route => {
      const request = route.request(); const target = new URL(request.url());
      if (target.pathname === '/api/auth/telegram') return route.fulfill({json: {userId: person.userId}});
      const payload = request.postData() ? request.postDataJSON() : undefined;
      const create = request.method() === 'POST' && target.pathname.endsWith('/chat/boards');
      if (create) creates.push(payload);
      const response = await app.inject({method: request.method() as 'GET' | 'POST' | 'PUT' | 'DELETE', url: target.pathname + target.search, payload, cookies: {session: person.token}});
      if (create && lost && response.statusCode === 200) { lost = false; return route.abort('failed'); }
      return route.fulfill({status: response.statusCode, contentType: 'application/json', body: response.body});
    });
    await mkdir(evidence, {recursive: true});
    const shot = async (name: string) => {
      await page.evaluate(() => document.fonts.ready);
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
      await page.screenshot({path: `${evidence}/issue176-${name}-${width}.png`});
    };
    await page.goto('/');
    await expect(page.getByRole('button', {name: 'Команда «Направления»', exact: true})).toBeVisible();
    await expect(page.getByRole('dialog', {name: 'Доски чата', exact: true})).toHaveCount(0);
    await page.getByRole('button', {name: 'Команда «Направления»', exact: true}).click();
    await page.getByRole('button', {name: 'Доски чата · Команда «Направления»'}).click();
    await page.route('**/api/boards/*/chat/link', route => route.abort('failed'), {times: 1});
    await page.getByRole('button', {name: 'Получить общую ссылку'}).click();
    await expect(page.getByRole('alert')).toBeVisible();
    await page.getByRole('button', {name: 'Получить общую ссылку'}).click();
    await expect(page.getByRole('textbox', {name: 'Общая ссылка чата'})).toBeVisible();
    common = new URL(await page.getByRole('textbox', {name: 'Общая ссылка чата'}).inputValue()).searchParams.get('startapp')!;
    expect(common).toMatch(/^board_[A-Za-z0-9_-]{32}$/);
    startToken = common;
    await page.getByRole('textbox', {name: 'Общая ссылка чата'}).focus();
    expect(await page.getByRole('textbox', {name: 'Общая ссылка чата'}).evaluate((input: HTMLInputElement) => input.selectionStart === 0 && input.selectionEnd === input.value.length)).toBe(true);
    await shot('general-link');
    await page.evaluate(() => document.documentElement.style.fontSize = '200%');
    await shot('general-link-text200');
    await page.evaluate(() => document.documentElement.style.fontSize = '');
    await page.reload();
    await expect(page.getByRole('dialog', {name: 'Доски чата', exact: true})).toHaveCount(0);
    await page.getByRole('button', {name: 'Команда «Направления»', exact: true}).click();
    await page.getByRole('button', {name: 'Доски чата · Команда «Направления»'}).click();
    await page.getByRole('button', {name: 'Добавить доску', exact: true}).click();
    const name = `Продуктовое направление ${'длинное '.repeat(8)}`.trim();
    await page.getByRole('textbox', {name: 'Название доски'}).fill(name);
    await expect(page.getByRole('button', {name: 'Создать', exact: true})).toBeDisabled();
    await page.getByRole('checkbox', {name: 'Подтверждаю состав и замену старых приглашений'}).check();
    await db.query("UPDATE memberships SET role = 'admin' WHERE board_id = $1 AND user_id = $2", [root.id, member.userId]);
    await page.getByRole('button', {name: 'Создать', exact: true}).click();
    await expect(page.getByRole('alert')).toContainText('актуальный состав');
    await page.getByRole('checkbox', {name: 'Подтверждаю состав и замену старых приглашений'}).check();
    await shot('confirmation');
    await page.evaluate(() => document.documentElement.style.fontSize = '200%');
    await shot('text200');
    await page.evaluate(() => document.documentElement.style.fontSize = '');
    await page.setViewportSize({width, height: 430});
    await page.getByRole('textbox', {name: 'Название доски'}).focus();
    await expect.poll(() => page.getByRole('textbox', {name: 'Название доски'}).evaluate(input => {
      const field = input.getBoundingClientRect(), sheet = input.closest('[role="dialog"]')!.getBoundingClientRect();
      return field.top >= sheet.top && field.bottom <= Math.min(sheet.bottom, innerHeight) ? 'visible'
        : JSON.stringify({field, sheet, active: document.activeElement?.tagName, scroll: input.closest('[role="dialog"]')!.scrollTop});
    })).toBe('visible');
    await shot('keyboard-viewport');
    await page.setViewportSize({width, height: 844});
    lost = true;
    await page.getByRole('button', {name: 'Создать', exact: true}).click();
    await expect(page.getByRole('button', {name: 'Проверить создание', exact: true})).toBeEnabled();
    await expect(page.getByRole('alert')).toContainText('Нет подтверждения сервера');
    await shot('lost-response');
    await page.route('**/api/boards/*/chat/boards', route => route.fulfill({status: 403, json: {error: 'Доступ временно закрыт'}}), {times: 1});
    await page.getByRole('button', {name: 'Проверить создание', exact: true}).click();
    await expect(page.getByRole('alert')).toContainText('Доступ временно закрыт');
    expect(await page.evaluate(() => Object.keys(localStorage).some(key => key.startsWith('tasks.chat-create.')))).toBe(true);
    await page.reload();
    await page.getByRole('button', {name: 'Проверить создание', exact: true}).click();
    await expect(page.getByRole('button', {name, exact: true})).toBeVisible();
    expect(creates).toHaveLength(3); expect(creates[1].requestId).toBe(creates[2].requestId);
    const children = (await db.query('SELECT id FROM boards WHERE chat_root_id = $1 AND id <> $1', [root.id])).rows;
    expect(children).toHaveLength(1); const childId = children[0].id;
    await shot('empty-direction');
    await page.reload();
    await expect(page.getByRole('dialog', {name: 'Доски чата', exact: true})).toBeVisible();
    await expect(page.getByRole('radio')).toHaveCount(2);
    await shot('chooser');
    startToken = direct; await page.reload();
    await expect(page.getByRole('button', {name: 'Команда «Направления»', exact: true})).toBeVisible();
    await expect(page.getByRole('dialog', {name: 'Доски чата', exact: true})).toHaveCount(0);
    await page.getByRole('button', {name: 'Настройки', exact: true}).click();
    await page.getByRole('button', {name: /Автоматизация/}).click();
    await page.getByRole('button', {name: /Команда «Направления»/}).click();
    await page.getByRole('button', {name: 'Публикации в чат', exact: true}).click();
    const daily = page.getByRole('group', {name: 'План дня', exact: true});
    await expect(daily.getByRole('checkbox', {name, exact: true})).not.toBeChecked();
    await daily.getByRole('checkbox', {name: 'Команда «Направления»', exact: true}).uncheck();
    await expect(daily.getByRole('status').filter({hasText: 'Доски не выбраны'})).toBeVisible();
    await expect(daily.getByRole('status').filter({hasText: 'Сохранено'})).toBeVisible();
    await shot('empty-summary');
    expect((await db.query("SELECT included_board_ids FROM publication_schedules WHERE board_id = $1 AND kind = 'daily'", [root.id])).rows[0].included_board_ids).toEqual([]);
    await daily.getByRole('checkbox', {name, exact: true}).check();
    await expect(daily.getByRole('status').filter({hasText: 'Сохранено'})).toBeVisible();
    expect((await db.query("SELECT included_board_ids FROM publication_schedules WHERE board_id = $1 AND kind = 'daily'", [root.id])).rows[0].included_board_ids).toEqual([childId]);
    await shot('selected-summary');
    person = member; startToken = common; await page.reload();
    await expect(page.getByRole('dialog', {name: 'Доски чата', exact: true})).toBeVisible();
    await expect(page.getByRole('button', {name: 'Добавить доску', exact: true})).toHaveCount(0);
    await expect(page.getByRole('button', {name: 'Получить общую ссылку'})).toHaveCount(0);
    await page.getByRole('radio', {name: new RegExp(name)}).click();
    await expect(page.getByRole('button', {name, exact: true})).toBeVisible();
    const revoked = await app.inject({method: 'DELETE', url: `/api/boards/${root.id}/chat/members/${member.userId}`, cookies: {session: owner.token}});
    expect(revoked.statusCode).toBe(200);
    await page.evaluate(() => window.dispatchEvent(new Event('focus')));
    await expect(page.getByRole('heading', {name: 'Доступ закрыт'})).toBeVisible();
    await shot('access-revoked');
    expect(errors).toEqual([]);
  } finally {
    globalThis.fetch = originalFetch; await app.close();
    await db.query('DELETE FROM boards WHERE chat_root_id = $1 OR owner_user_id = ANY($2::bigint[])', [root.id, [owner.userId, member.userId]]);
    await db.query('DELETE FROM users WHERE id = ANY($1::bigint[])', [[owner.userId, member.userId]]); await db.end();
  }
});
